[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$workRoot = Join-Path $repoRoot "work"
$indexRoot = Join-Path $workRoot "_index"
$indexPath = Join-Path $indexRoot "records.md"

function Read-RecordMetadata {
    param([Parameter(Mandatory = $true)][string]$ContextPath)

    $lines = Get-Content -LiteralPath $ContextPath
    if ($lines.Count -lt 3 -or $lines[0] -ne "---") {
        throw "Record context has no YAML frontmatter: $ContextPath"
    }

    $metadata = @{}
    for ($index = 1; $index -lt $lines.Count; $index++) {
        $line = $lines[$index]
        if ($line -eq "---") {
            break
        }

        if ($line -match '^(?<key>[a-z_]+):\s*(?<value>.*)$') {
            $metadata[$matches.key] = $matches.value.Trim().Trim('"')
        }
    }

    foreach ($requiredKey in @("type", "id", "title", "status", "current_stage")) {
        if (-not $metadata.ContainsKey($requiredKey) -or [string]::IsNullOrWhiteSpace($metadata[$requiredKey])) {
            throw "Record context has no '$requiredKey' value: $ContextPath"
        }
    }

    return $metadata
}

$records = New-Object System.Collections.Generic.List[object]
foreach ($state in @("active", "closed")) {
    $stateRoot = Join-Path $workRoot $state
    if (-not (Test-Path -LiteralPath $stateRoot -PathType Container)) {
        continue
    }

    Get-ChildItem -LiteralPath $stateRoot -Directory | Sort-Object Name | ForEach-Object {
        $contextPath = Join-Path $_.FullName "CONTEXT.md"
        if (-not (Test-Path -LiteralPath $contextPath -PathType Leaf)) {
            throw "Record folder has no CONTEXT.md: $($_.FullName)"
        }

        $metadata = Read-RecordMetadata -ContextPath $contextPath
        if ($metadata.status -ne $state) {
            throw "Folder state '$state' does not match record status '$($metadata.status)': $contextPath"
        }

        $records.Add([pscustomobject]@{
            State = $state
            Id = $metadata.id
            Title = $metadata.title
            Stage = $metadata.current_stage
            Link = "../$state/$($_.Name)/CONTEXT.md"
        })
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Change record index")
$lines.Add("")
$lines.Add("> GENERATED by ``scripts/rebuild-work-index.ps1``. Do not edit this file by hand.")
$lines.Add("")
$lines.Add("| State | Record | Current stage | Contract |")
$lines.Add("|---|---|---|---|")

foreach ($record in ($records | Sort-Object State, Id)) {
    $lines.Add("| $($record.State) | $($record.Title) | ``$($record.Stage)`` | [$($record.Id)]($($record.Link)) |")
}

New-Item -ItemType Directory -Path $indexRoot -Force | Out-Null
[System.IO.File]::WriteAllLines($indexPath, $lines, [System.Text.UTF8Encoding]::new($false))

Write-Host "Wrote $($records.Count) records to $indexPath"
